name: Build and Push Helm Chart
on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'Chart version to set'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE: vidis-provisionierungs-api
  REPOSITORY: ${{ github.repository_owner }}

jobs:
  build:
    name: Build Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: lowercase repository
        run: echo "REPOSITORY=${REPOSITORY,,}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Push Chart
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          name: ${{ env.IMAGE }}
          tag: ${{ inputs.chart_version }}
          path: charts/provisionierungs-api
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
